import { Menu } from "@/types/menu";

interface RawPage {
  title: string;
  unitEntity: string;
  urlExample: string;
  content: string;
  columns: string[];
  path: string;
  infiniteScroll: boolean;
  additionalColumnsFromRowUrl: string[];
}

interface Page {
  title: string;
  unitEntity: string;
  urlExample: string;
  content: string;
  columns: string[];
  aiGenerated: boolean;
  infiniteScroll?: boolean;
  additionalColumnsFromRowUrl: string[];
}

const HumanPages: RawPage[] = [
  {
    title: "Google Businesses",
    unitEntity: "Business",
    urlExample: "https://www.google.com/maps/search/Restaurants/",
    content: "This is content for page 1",
    path: "google",
    infiniteScroll: true,
    columns: [
      "Business Name",
      "Address",
      "Business Hours",
      "Review Count",
      "Rating",
    ],
    additionalColumnsFromRowUrl: ["Website", "Phone Number"],
  },
  // {
  //   title: "Kijiji Marketplace",
  //   urlExample: "https://www.kijiji.ca/b-marketplace/ontario/",
  //   content: "This is content for page 2",
  //   columns: ["Title", "Price", "Location", "Description", "Post Date"],
  //   path: "kijiji",
  // },
];

const AIGeneratedPages: RawPage[] = [
  {
    title: "Google Businesses",
    unitEntity: "Business",
    urlExample: "https://www.google.com/maps/search/Restaurants/",
    content: "This is content for page 1",
    path: "google",
    infiniteScroll: true,
    columns: [
      "Business Name",
      "Address",
      "Business Hours",
      "Review Count",
      "Rating",
    ],
    additionalColumnsFromRowUrl: ["Website", "Phone Number"],
  },
  {
    title: "Amazon Products",
    unitEntity: "Product",
    urlExample: "https://www.amazon.com/s?k=laptop",
    content: "This is content for Amazon products page.",
    path: "amazon",
    infiniteScroll: true,
    columns: [
      "Product Name",
      "Price",
      "Rating",
      "Review Count",
      "Availability",
    ],
    additionalColumnsFromRowUrl: ["Seller", "Shipping Options"],
  },
  {
    title: "YouTube Videos",
    unitEntity: "Video",
    urlExample: "https://www.youtube.com/results?search_query=cooking",
    content: "This is content for YouTube videos page.",
    path: "youtube",
    infiniteScroll: true,
    columns: [
      "Video Title",
      "Channel Name",
      "Views",
      "Upload Date",
      "Duration",
    ],
    additionalColumnsFromRowUrl: ["Description", "Tags"],
  },
  {
    title: "Wikipedia Articles",
    unitEntity: "Article",
    urlExample: "https://en.wikipedia.org/wiki/Solar_system",
    content: "This is content for Wikipedia articles page.",
    path: "wikipedia",
    infiniteScroll: false,
    columns: [
      "Article Title",
      "Summary",
      "Last Edited Date",
      "Contributors",
      "References Count",
    ],
    additionalColumnsFromRowUrl: ["Categories", "External Links"],
  },
  {
    title: "Twitter Posts",
    unitEntity: "Tweet",
    urlExample: "https://twitter.com/search?q=tech",
    content: "This is content for Twitter posts page.",
    path: "twitter",
    infiniteScroll: true,
    columns: ["Username", "Tweet Content", "Likes", "Retweets", "Post Date"],
    additionalColumnsFromRowUrl: ["Replies", "Hashtags"],
  },
  {
    title: "Facebook Posts",
    unitEntity: "Post",
    urlExample: "https://www.facebook.com/search/top?q=fitness",
    content: "This is content for Facebook posts page.",
    path: "facebook",
    infiniteScroll: true,
    columns: ["Post Author", "Content", "Likes", "Comments", "Shares"],
    additionalColumnsFromRowUrl: ["Reactions", "Post Date"],
  },
  {
    title: "Instagram Photos",
    unitEntity: "Photo",
    urlExample: "https://www.instagram.com/explore/tags/travel/",
    content: "This is content for Instagram photos page.",
    path: "instagram",
    infiniteScroll: true,
    columns: ["Username", "Caption", "Likes", "Comments", "Post Date"],
    additionalColumnsFromRowUrl: ["Location", "Tags"],
  },
  {
    title: "Reddit Posts",
    unitEntity: "Post",
    urlExample: "https://www.reddit.com/r/programming/",
    content: "This is content for Reddit posts page.",
    path: "reddit",
    infiniteScroll: true,
    columns: ["Post Title", "Subreddit", "Upvotes", "Comments", "Post Date"],
    additionalColumnsFromRowUrl: ["Author", "Flair"],
  },
  {
    title: "LinkedIn Jobs",
    unitEntity: "Job",
    urlExample: "https://www.linkedin.com/jobs/search/?keywords=developer",
    content: "This is content for LinkedIn jobs page.",
    path: "linkedin",
    infiniteScroll: true,
    columns: ["Job Title", "Company", "Location", "Posted Date", "Job Type"],
    additionalColumnsFromRowUrl: ["Job Description", "Salary"],
  },
  {
    title: "Netflix Shows",
    unitEntity: "Show",
    urlExample: "https://www.netflix.com/browse/genre/83",
    content: "This is content for Netflix shows page.",
    path: "netflix",
    infiniteScroll: true,
    columns: ["Show Title", "Genre", "Seasons", "Episodes", "Rating"],
    additionalColumnsFromRowUrl: ["Cast", "Description"],
  },
  {
    title: "eBay Listings",
    unitEntity: "Product",
    urlExample: "https://www.ebay.com/sch/i.html?_nkw=smartphone",
    content: "This is content for eBay listings page.",
    path: "ebay",
    infiniteScroll: true,
    columns: ["Product Name", "Price", "Bids", "Condition", "Shipping"],
    additionalColumnsFromRowUrl: ["Seller Info", "Location"],
  },
  {
    title: "Pinterest Pins",
    unitEntity: "Pin",
    urlExample: "https://www.pinterest.com/search/pins/?q=recipes",
    content: "This is content for Pinterest pins page.",
    path: "pinterest",
    infiniteScroll: true,
    columns: ["Pin Title", "User", "Saves", "Comments", "Description"],
    additionalColumnsFromRowUrl: ["Link", "Tags"],
  },
  {
    title: "TikTok Videos",
    unitEntity: "Video",
    urlExample: "https://www.tiktok.com/tag/dance",
    content: "This is content for TikTok videos page.",
    path: "tiktok",
    infiniteScroll: true,
    columns: ["Username", "Video Title", "Likes", "Comments", "Shares"],
    additionalColumnsFromRowUrl: ["Tags", "Duration"],
  },
  {
    title: "Spotify Playlists",
    unitEntity: "Playlist",
    urlExample: "https://open.spotify.com/genre/rock",
    content: "This is content for Spotify playlists page.",
    path: "spotify",
    infiniteScroll: true,
    columns: [
      "Playlist Name",
      "Creator",
      "Tracks Count",
      "Followers",
      "Duration",
    ],
    additionalColumnsFromRowUrl: ["Description", "Genre"],
  },
  {
    title: "Tripadvisor Hotels",
    unitEntity: "Hotel",
    urlExample: "https://www.tripadvisor.com/Hotels",
    content: "This is content for Tripadvisor hotels page.",
    path: "tripadvisor",
    infiniteScroll: true,
    columns: ["Hotel Name", "Location", "Rating", "Reviews", "Price"],
    additionalColumnsFromRowUrl: ["Amenities", "Contact Info"],
  },
  {
    title: "Airbnb Listings",
    unitEntity: "Listing",
    urlExample: "https://www.airbnb.com/s/homes",
    content: "This is content for Airbnb listings page.",
    path: "airbnb",
    infiniteScroll: true,
    columns: [
      "Property Name",
      "Location",
      "Price per Night",
      "Rating",
      "Reviews",
    ],
    additionalColumnsFromRowUrl: ["Host Info", "Cancellation Policy"],
  },
  {
    title: "GitHub Repositories",
    unitEntity: "Repository",
    urlExample: "https://github.com/search?q=machine+learning",
    content: "This is content for GitHub repositories page.",
    path: "github",
    infiniteScroll: true,
    columns: ["Repo Name", "Owner", "Stars", "Forks", "Last Updated"],
    additionalColumnsFromRowUrl: ["Language", "License"],
  },
  {
    title: "IMDB Movies",
    unitEntity: "Movie",
    urlExample: "https://www.imdb.com/search/title/?genres=action",
    content: "This is content for IMDB movies page.",
    path: "imdb",
    infiniteScroll: false,
    columns: ["Movie Title", "Director", "Release Year", "Rating", "Runtime"],
    additionalColumnsFromRowUrl: ["Cast", "Genres"],
  },
  {
    title: "SoundCloud Tracks",
    unitEntity: "Track",
    urlExample: "https://soundcloud.com/search?q=hip+hop",
    content: "This is content for SoundCloud tracks page.",
    path: "soundcloud",
    infiniteScroll: true,
    columns: ["Track Title", "Artist", "Plays", "Likes", "Comments"],
    additionalColumnsFromRowUrl: ["Release Date", "Genre"],
  },
  {
    title: "Twitch Streams",
    unitEntity: "Stream",
    urlExample: "https://www.twitch.tv/directory/game/Valorant",
    content: "This is content for Twitch streams page.",
    path: "twitch",
    infiniteScroll: true,
    columns: ["Stream Title", "Streamer", "Viewers", "Game", "Language"],
    additionalColumnsFromRowUrl: ["Stream Duration", "Tags"],
  },
  {
    title: "Yelp Restaurants",
    unitEntity: "Restaurant",
    urlExample: "https://www.yelp.com/search?cflt=restaurants",
    content: "This is content for Yelp restaurants page.",
    path: "yelp",
    infiniteScroll: true,
    columns: [
      "Restaurant Name",
      "Location",
      "Rating",
      "Review Count",
      "Price Range",
    ],
    additionalColumnsFromRowUrl: ["Cuisine Type", "Phone Number"],
  },
  {
    title: "TikTok Videos",
    unitEntity: "Video",
    urlExample: "https://www.tiktok.com/tag/dance",
    content: "This is content for TikTok videos page.",
    path: "tiktok",
    infiniteScroll: true,
    columns: ["Username", "Video Title", "Likes", "Comments", "Shares"],
    additionalColumnsFromRowUrl: ["Tags", "Duration"],
  },
  {
    title: "Spotify Playlists",
    unitEntity: "Playlist",
    urlExample: "https://open.spotify.com/genre/rock",
    content: "This is content for Spotify playlists page.",
    path: "spotify",
    infiniteScroll: true,
    columns: [
      "Playlist Name",
      "Creator",
      "Tracks Count",
      "Followers",
      "Duration",
    ],
    additionalColumnsFromRowUrl: ["Description", "Genre"],
  },
  {
    title: "Tripadvisor Hotels",
    unitEntity: "Hotel",
    urlExample: "https://www.tripadvisor.com/Hotels",
    content: "This is content for Tripadvisor hotels page.",
    path: "tripadvisor",
    infiniteScroll: true,
    columns: ["Hotel Name", "Location", "Rating", "Reviews", "Price"],
    additionalColumnsFromRowUrl: ["Amenities", "Contact Info"],
  },
  {
    title: "Etsy Products",
    unitEntity: "Product",
    urlExample: "https://www.etsy.com/search?q=jewelry",
    content: "This is content for Etsy products page.",
    path: "etsy",
    infiniteScroll: true,
    columns: ["Product Name", "Price", "Seller", "Review Count", "Rating"],
    additionalColumnsFromRowUrl: ["Materials", "Shipping Time"],
  },
  {
    title: "Craigslist Listings",
    unitEntity: "Listing",
    urlExample: "https://www.craigslist.org/search/sss",
    content: "This is content for Craigslist listings page.",
    path: "craigslist",
    infiniteScroll: false,
    columns: ["Title", "Price", "Location", "Date Posted", "Category"],
    additionalColumnsFromRowUrl: ["Description", "Contact Info"],
  },
  {
    title: "Quora Questions",
    unitEntity: "Question",
    urlExample: "https://www.quora.com/search?q=technology",
    content: "This is content for Quora questions page.",
    path: "quora",
    infiniteScroll: true,
    columns: [
      "Question Title",
      "Asked By",
      "Answer Count",
      "Views",
      "Last Activity",
    ],
    additionalColumnsFromRowUrl: ["Tags", "Related Topics"],
  },
  {
    title: "Medium Articles",
    unitEntity: "Article",
    urlExample: "https://medium.com/search?q=business",
    content: "This is content for Medium articles page.",
    path: "medium",
    infiniteScroll: true,
    columns: [
      "Article Title",
      "Author",
      "Reading Time",
      "Claps",
      "Publication Date",
    ],
    additionalColumnsFromRowUrl: ["Tags", "Responses"],
  },
  {
    title: "Bing Images",
    unitEntity: "Image",
    urlExample: "https://www.bing.com/images/search?q=landscape",
    content: "This is content for Bing images page.",
    path: "bing",
    infiniteScroll: true,
    columns: ["Image Title", "Source", "Dimensions", "File Size", "License"],
    additionalColumnsFromRowUrl: ["Photographer", "Tags"],
  },
  {
    title: "Vimeo Videos",
    unitEntity: "Video",
    urlExample: "https://vimeo.com/search?q=animation",
    content: "This is content for Vimeo videos page.",
    path: "vimeo",
    infiniteScroll: true,
    columns: ["Video Title", "Creator", "Views", "Likes", "Duration"],
    additionalColumnsFromRowUrl: ["Description", "Tags"],
  },
  {
    title: "DeviantArt Artworks",
    unitEntity: "Artwork",
    urlExample: "https://www.deviantart.com/search?q=fantasy",
    content: "This is content for DeviantArt artworks page.",
    path: "deviantart",
    infiniteScroll: true,
    columns: ["Title", "Artist", "Views", "Favorites", "Comments"],
    additionalColumnsFromRowUrl: ["Category", "Tags"],
  },
  {
    title: "Hacker News Posts",
    unitEntity: "Post",
    urlExample: "https://news.ycombinator.com/",
    content: "This is content for Hacker News posts page.",
    path: "hackernews",
    infiniteScroll: false,
    columns: ["Title", "Points", "Comments", "Author", "Posted Time"],
    additionalColumnsFromRowUrl: ["Domain", "Discussion Link"],
  },
  {
    title: "GitHub Gists",
    unitEntity: "Gist",
    urlExample: "https://gist.github.com/discover",
    content: "This is content for GitHub gists page.",
    path: "github-gists",
    infiniteScroll: true,
    columns: ["Gist Description", "Author", "Files Count", "Forks", "Stars"],
    additionalColumnsFromRowUrl: ["Language", "Last Updated"],
  },
  {
    title: "Weibo Posts",
    unitEntity: "Post",
    urlExample: "https://weibo.com/",
    content: "This is content for Weibo posts page.",
    path: "weibo",
    infiniteScroll: true,
    columns: ["User", "Content", "Likes", "Comments", "Shares"],
    additionalColumnsFromRowUrl: ["Tags", "Post Date"],
  },
  {
    title: "Tumblr Posts",
    unitEntity: "Post",
    urlExample: "https://www.tumblr.com/search/travel",
    content: "This is content for Tumblr posts page.",
    path: "tumblr",
    infiniteScroll: true,
    columns: ["Post Title", "Author", "Notes", "Post Date", "Tags"],
    additionalColumnsFromRowUrl: ["Description", "Images"],
  },
  {
    title: "SoundCloud Playlists",
    unitEntity: "Playlist",
    urlExample: "https://soundcloud.com/search/sets?q=pop",
    content: "This is content for SoundCloud playlists page.",
    path: "soundcloud-playlists",
    infiniteScroll: true,
    columns: ["Playlist Name", "Creator", "Tracks Count", "Plays", "Likes"],
    additionalColumnsFromRowUrl: ["Genre", "Tags"],
  },
  {
    title: "Product Hunt Products",
    unitEntity: "Product",
    urlExample: "https://www.producthunt.com/",
    content: "This is content for Product Hunt products page.",
    path: "producthunt",
    infiniteScroll: true,
    columns: ["Product Name", "Description", "Upvotes", "Comments", "Category"],
    additionalColumnsFromRowUrl: ["Website", "Launch Date"],
  },
  {
    title: "Behance Projects",
    unitEntity: "Project",
    urlExample:
      "https://www.behance.net/search/projects?search=graphic%20design",
    content: "This is content for Behance projects page.",
    path: "behance",
    infiniteScroll: true,
    columns: ["Project Title", "Creator", "Views", "Appreciations", "Comments"],
    additionalColumnsFromRowUrl: ["Tags", "Category"],
  },
  {
    title: "Kickstarter Campaigns",
    unitEntity: "Campaign",
    urlExample: "https://www.kickstarter.com/discover",
    content: "This is content for Kickstarter campaigns page.",
    path: "kickstarter",
    infiniteScroll: true,
    columns: ["Campaign Name", "Creator", "Goal", "Pledged", "Backers"],
    additionalColumnsFromRowUrl: ["Category", "End Date"],
  },
  {
    title: "Udemy Courses",
    unitEntity: "Course",
    urlExample: "https://www.udemy.com/courses/search/?q=programming",
    content: "This is content for Udemy courses page.",
    path: "udemy",
    infiniteScroll: true,
    columns: [
      "Course Title",
      "Instructor",
      "Rating",
      "Students Enrolled",
      "Price",
    ],
    additionalColumnsFromRowUrl: ["Duration", "Language"],
  },
  {
    title: "Coursera Courses",
    unitEntity: "Course",
    urlExample: "https://www.coursera.org/search?query=data%20science",
    content: "This is content for Coursera courses page.",
    path: "coursera",
    infiniteScroll: true,
    columns: [
      "Course Title",
      "University",
      "Rating",
      "Enrollments",
      "Duration",
    ],
    additionalColumnsFromRowUrl: ["Level", "Language"],
  },
  {
    title: "Dribbble Designs",
    unitEntity: "Design",
    urlExample: "https://dribbble.com/search/shots/popular/web",
    content: "This is content for Dribbble designs page.",
    path: "dribbble",
    infiniteScroll: true,
    columns: ["Design Title", "Designer", "Likes", "Views", "Comments"],
    additionalColumnsFromRowUrl: ["Tags", "Tools Used"],
  },
];

// Define the structure of pages object with key as string and value as Page
export const pages: Record<string, Page> = {};
HumanPages.forEach((page) => {
  pages[page.path] = {
    title: page.title,
    unitEntity: page.unitEntity,
    urlExample: page.urlExample,
    content: page.content,
    aiGenerated: false,
    columns: page.columns,
    infiniteScroll: page.infiniteScroll,
    additionalColumnsFromRowUrl: page.additionalColumnsFromRowUrl,
  };
});

AIGeneratedPages.forEach((page) => {
  pages[page.path] = {
    title: page.title,
    unitEntity: page.unitEntity,
    content: page.content,
    aiGenerated: true,
    columns: page.columns,
    urlExample: page.urlExample,
    infiniteScroll: page.infiniteScroll,
    additionalColumnsFromRowUrl: page.additionalColumnsFromRowUrl,
  };
});

const menuData: Menu[] = [
  {
    id: 1,
    title: "Home",
    path: "/",
    newTab: false,
    prefetch: true,
  },
  {
    id: 4,
    title: "Scraping Guides",
    newTab: false,
    prefetch: true,
    submenu: [
      ...HumanPages.map((page, index) => ({
        id: index + 10,
        title: page.title,
        path: `/scraping-guides/${page.path}`,
        newTab: false,
        prefetch: true,
      })),
      ...AIGeneratedPages.map((page, index) => ({
        id: index + 10,
        title: page.title,
        path: `/scraping-guides/${page.path}`,
        newTab: false,
        prefetch: false,
      })),
    ],
  },
];
export default menuData;
